import type { Metadata } from "next";
import { Averia_Serif_Libre, Inter } from "next/font/google";

import "./globals.css";

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const averiaSerifLibre = Averia_Serif_Libre({
  weight: ["700"], 
  subsets: ["latin"],
  variable: "--font-averia"
})

const inter = Inter({
  weight: ["400", "500"], 
  subsets: ["latin"],
  variable: "--font-inter"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${averiaSerifLibre.className} ${inter.className} antialiased max-w-[90rem] mx-auto`}
      >
        <Header />
        <main className="font-inter">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
